apiVersion: v1
kind: Pod
metadata:
  name: echo
  namespace: production
spec:
  containers:
    - name: echo
      image: k8s.gcr.io/echoserver:1.4
      imagePullPolicy: IfNotPresent
#  nodeSelector:
#    env: production